[package]
name = "rust-fit-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
syn = "2.0.42"
proc-macro2 = "1.0.70"
quote = "1.0.33"
prettyplease = "0.2.15"
serde = { version = "1.0.193", features = ["serde_derive"] }
anyhow = "=1.0.75"
heck = "0.4.1"
